### ISSUE TITLE
RSS feed for blog?

### ISSUE THREAD

**Issue by case** [Police-Data-Accessibility-Project/PDAP.io#40]
Hello,

I was hoping to subscribe to your blog via an RSS reader, but I can't find an RSS / Atom / etc. XML feed anywhere in the page source.

Wondering if you'd be game to add a feed?

Thanks!
-Eric

**Comment by josh-chamberlain** [comment]
@case this is a good idea—we recently moved the blog because it had a bunch of [outstanding issues](https://github.com/Police-Data-Accessibility-Project/PDAP.io/pull/51).

Now it's just simply kept in our docs which are in gitbook. I tried installing this: https://github.com/denysdovhan/gitbook-plugin-rss

but I think it's out of date, the book.json file didn't want to parse. I got a note that the gitbook team will get back to me on it.

**Comment by josh-chamberlain** [comment]
@case I was able to get this to work: http://fetchrss.com/rss/6146cab9ead6fc081b5938226146ca903553905be00a4212.xml

pretty neat.

**Comment by josh-chamberlain** [comment]
<img width="288" alt="Screen Shot 2021-09-19 at 1 31 34 AM" src="https://user-images.githubusercontent.com/30379833/133916597-4a582181-bfae-4d13-b8c4-fe355027c8c7.png">

Gonna call it closed for now, even though it's a bit hacky—please reopen if that doesn't work for you!
